sudo: required
services:
  - docker
language: node_js
os: linux
cache: yarn
node_js:
  - stable
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker pull redis:3.2.11-alpine
  - docker pull node:9.9.0-alpine
  - docker network create --driver bridge test-net
  - docker run -d --rm --name redis --network test-net redis:3.2.11-alpine
  - docker ps -a
script:
  - npm test
after_success:
  - npm run test:coverage && npx codecov
deploy:
  provider: npm
  email: anton@mokr.org
  api_key:
    secure: LWAzaFOtZBosvfbYogIVXQkI1rZaGo4IPOJxtUAxOunembfClA+1qHcI0JyDlZ4hpar7zoS+ScJyPoDzQC6RbjBr1Wt6woC3aK+0Er0yQ4CosbzcRmNvIbPH8mGTIRJwiRkepRoHSnhVPAnGgMA87FytWk5uZtKMwRVYE0engR5XiDco0uGai7Q6Fso4a10U62Jn+5Q1ElE2nHrSolExNpWIy+YD3WGzHmr3pdJI4D+VY5x/GBDYeoswQ6XHpFmdrp/RX1VSgH/ZGoG2TPGZTCTBUDPfYrtHlM7DVUWsmKcMI22pKAasuKNthhNJGzKF7m+AwhYVDcezSn+aJiFdTm0D9NjDmHmhr4b4OiCHR+ej/W010pyA57xK1ByxCXpdHmNOLE8dY88VNddvNyTy4o8KqY4VwSUfLXWaNPFN8UnzOoGmQB5BILyTyd0CJIVmqJMc6bT3GnE4/V55ZnCfd3h0WV1148DkcJIKJa2QC8BOoPTP1fxDiNOCeCR6TwHeXpjdYigyw7QiDp9VrULo9397CSJITGFqwUVCbLinAkMYt0uCbIozXC9DvyCnmZGZ5SiwXXyh3Q4dsj95wHwVodeIFAFBTEKqwrkBt2blfZpuLULbSxq/xvMpyRdhKGHVbVfK8VXPRH6y5aRZyN+nEGGnwbN+P94K5WboHf4pn+g=
  on:
    tags: true
    repo: amokrushin/redis-queue
